### ISSUE TITLE
Multiple Relations per Sentence

### ISSUE THREAD

**Issue by pvcastro** [thunlp/RE-Context-or-Names#11]
Hi @h-peng17 !

How do you feel about applying the CP pre-training to sentences containing multiple pairs of different types of relations? The first concern would be that we would end up having the same sentence in different "bags" per relations. Even if we do perform the training in a simpler subset of sentences, containing one pair per sentence, do you think applying this resulting model on a more complex dataset with multiple relations and overlap, would yield better results?

Thanks!

**Comment by h-peng17** [comment]
We know in many RE dataset such as TACRED, one same sentence may contain many different relations(with different entity pairs), and the dataset treats them as different training/testing instances. Because we use Entity Marker Starter to get contextual relational representation about entity pairs, so I think CP can be used on a more complex dataset. 
You can read Supervised Contrastive Leanring(https://arxiv.org/abs/2004.11362) which is similar with our idea, but they apply on CV task. I think CP used in this paper(i.e. apply on CV) is more difficult than used in sentences. So CP pre-training has the potential to model more complex data.

**Comment by pvcastro** [comment]
So the same sentence in TACRED is used as different instances, according to each entity pair? I thought the sentences hadn't been exhaustively annotated, and I was under the impression that they were only used once, with a single pair of entities, even though others are present in them.

Do you think something in your code should be done to adapt to the scenarios in which a sentence might be used as both negative and positive samples? If the sentence contains different relations on it.

**Comment by h-peng17** [comment]
Just set `--entity_marker` on and our model can handle this scenario.
