### ISSUE TITLE
Problem computing loss on custom dataset

### ISSUE THREAD

**Issue by pvcastro** [thunlp/RE-Context-or-Names#13]
Hi there @h-peng17 !

I'm having a hard time running the CP pretraining on my custom dataset. I have only four types of relations, and when a particular batch contains only one type of relation, I end up having no negative samples, and an exception is raised. Do you have some way to prevent this from happening, or should I adjust the batches manually, so it can have more than one type of relations?

Thanks!

**Comment by h-peng17** [comment]
You can see https://github.com/thunlp/RE-Context-or-Names/blob/1c0cff9bf3137862488ef2792e051c7db2a4fb8d/pretrain/code/dataset.py#L107. In __sample__ function, every relation has a set of postive pairs. For every positive pair in __getitem__, you can sample another positive pair of different relations.  That is, every instance returned from __getitem__ would be [sent1 for rel1; sent2 for rel1; sent1 for rel2, sent2 for rel2] instead of [sent1 for rel1; sent2 for rel1]. This will ensure that every batch will have positive pairs and negative pairs, even though the batch size is 1.
